version: "3"
services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - api
    env_file: ./backend/.env
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend-app
  frontend:
    build:
      context: ./frontend
    command: yarn dev
    depends_on:
      - backend
      - api
    volumes:
      - ./frontend:/frontend-app
      - ./frontend/package.json:/frontend-app/package.json
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
    command: npm start
    volumes:
      - ./api:/api-app
      - ./api/package.json:/api-app/package.json
    ports:
      - "3003:3003"
  db:
    image: postgres:11.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: